# samba-ubuntu.yml
---
- hosts: ubuntu
  remote_user: vagrant
  become: yes
  become_method: "sudo"

  handlers:
    - name: restart samba
      service:
              name: smbd 
              state: restarted
      service:
              name: nmbd
              state: restarted
  tasks:
    - name: Installer samba
      apt:
              name: samba 
              state: latest
    - name: Démarrer service samba
      service:
              name: smbd 
              state: started 
              enabled: true
    - name: Création du dossier public
      file:
              path: /srv/samba/commun
              owner: nobody
              group: nogroup
              state: directory
              mode: 0777
    - name: Ouvrir le firewall pour samba
      ufw:
              rule: allow
              name: Samba
    - name: Copier le fichier personnalisé de samba
      copy:
              src: /home/vagrant/ansible_samba/smb.conf 
              dest: /etc/samba/smb.conf
      notify:
              - restart samba
